baseURL: https://www.wabbitinc.com
languageCode: en-us
title: Wabbitinc
theme: ananke

params:
  subtitle: "Lola & Mike's Personal Site"
  #mainSections: ["post"]
  logo: "img/pitr-bunny-icon.png" # Expecting square dimensions
  favicon: "img/pitr-bunny-icon.ico"
  dateFormat: "January 2, 2006"
  commit: false
  rss: false
  comments: false
  readingTime: true
  wordCount: true
  useHLJS: true
  socialShare: false
  delayDisqus: false
  showRelatedPosts: false
  hideAuthor: true

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Tags
      url: tags
      weight: 2


