baseURL: https://www.wabbitinc.com
languageCode: en-us
title: Wabbitinc
theme: hugo-ink

params:
  width: 42rem
  description: Wabbitinc
  footer:
  rss:
  divider: '\2015\2015' # Set to false to remove divider below posts on homepage
  schema: true
  opengraph: true
  twittercards: false
  summaries: false

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Posts
      url: oldposts/
      weight: 2

taxonomies:
  tag: tags
